### PR TITLE
Add a dry-run mode to kano-settings-onboot

### PR DESCRIPTION
**Pull request by Ealdwulf**
This PR adds a --dry-run option to kano-settings-onboot which causes it to do nothing and to log all config changes and reboots.
It's not necessary for this release.
@skarbat @tombettany

### CODE REVIEW

**Comment by skarbat** [comment]
that's great @Ealdwulf !

**Comment by Ealdwulf** [comment]
Thanks @skarbat ; will  merge after release.

**Comment by tombettany** [comment]
@Ealdwulf Do we want to merge this in for the next release?

**Comment by Ealdwulf** [comment]
Probably a good idea @tombettany . If I make changes to kano-settings I'll rebase it.

**Comment by Ealdwulf** [comment]
Closing for rebase.

**Pull request closed without merging**
