### PR TITLE
Use alsa-utils to store HDMI vs speaker config

### PR DESCRIPTION
**Pull request by Ealdwulf**
Alsa-utils stores the volume and audio-route config.
We were also storing the audio route config in /etc/rc.audio and not telling alsa-utils about it.
The fix to https://github.com/KanoComputing/peldins/issues/1684 reloads the volume using alsa-utils after lxpanel is launched, this has the effect of using alsa-utils version of the audio-route config (confusingly, after the boot sound)

This PR removes our /etc/rc.audio in favour of using alsa-utils to store all of the audio config (ie, volume and HDMI vs speaker).

### CODE REVIEW

**Comment by alex5imon** [comment]
@skarbat @pazdera can you have a look at this please? No rc.audio needed

**Comment by skarbat** [comment]
It's good that we leverage this to `alsa`. Looks good to me @alex5imon @Ealdwulf

**Comment by alex5imon** [comment]
Please merge :+1:

**Comment by Ealdwulf** [comment]
Thanks! Merging...

**Pull request merged**
