### PR TITLE
Fixed opening Browser login from wireless settings

### PR DESCRIPTION
**Pull request by skarbat**
* The function to open the common browser was being referenced
   as a Gtk callback method, which would never work. Added a callback
   function which correctly calls the function to open the browser

cc @alex5imon @Ealdwulf

### CODE REVIEW

**Comment by alex5imon** [comment]
@pazdera @Ealdwulf  can you review this?

**Comment by Ealdwulf** [comment]
This looks okay to me @skarbat @pazdera @alex5imon . I also just tested it and I can now launch the browser.

**Comment by alex5imon** [comment]
Awesome thanks @Ealdwulf 

@skarbat please merge

**Comment by skarbat** [comment]
thanks @Ealdwulf @alex5imon !

**Pull request merged**
