### PR TITLE
Changed copy from Appearance to Style

### PR DESCRIPTION
**Pull request by radujipa**
- Changed the Copy on the `Appearance` app to `Style`
 - source code, including file names, also reflects this

@alex5imon @convolu could you please review this?

### CODE REVIEW

**Comment by radujipa** [comment]
related to https://github.com/KanoComputing/peldins/issues/2090

**Comment by radujipa** [comment]
bump @alex5imon @convolu

**Comment by convolu** [comment]
Sorry it took so long, fell through the cracks :-). Looks ok to me, are people happy with the copy?

**Comment by alex5imon** [comment]
Please merge :+1:

**Comment by radujipa** [comment]
Thanks @convolu @alex5imon , merging and rebasing `jessie`

**Pull request merged**
