### PR TITLE
Parental: Blacklist Google webcache and translate

### PR DESCRIPTION
**Pull request by tombettany**
KanoComputing/peldins#1692
Cached versions of blocked sites can be seen either by viewing Google's
webcache of the site or by translating the URL so block this in the
`/etc/hosts` blacklist mode of parental control. Do this by creating a
Kano list for blacklisting to supplement that supplied by
www.hostsfile.org/hosts.html. Updates the instructions in the  LICENSE
readme to reflect this extra step.

### CODE REVIEW

**Comment by alex5imon** [comment]
@tombettany please merge and assign ticket to @FMog :+1:

**Comment by alex5imon** [comment]
@tombettany let me commit the .gzip first...

**Comment by tombettany** [comment]
@alex5imon Are you updating the gzip from an update on www.hostsfile.org/hosts.html? If not, I did add the new websites into the current file.

**Comment by alex5imon** [comment]
No need to update the host list, we are at the latest version.

Merging...

**Pull request merged**
