### PR TITLE
Fix for Settings not showing es_AR keyboard layout in i18n img

### PR DESCRIPTION
**Pull request by radujipa**
When we [set the keyboard layout](https://github.com/KanoComputing/peldins/blob/jessie/Makefile#L554) according to the locale at image build time, kano-settings simply makes the changes, but it doesn't update its config file. This PR fixes that, so when you'd open Settings > Keyboard it should show the `es_AR` set value.

@tombettany @skarbat

### CODE REVIEW

**Comment by radujipa** [comment]
I have added a fix for https://trello.com/c/j9LuoVWl/337-missing-keys-on-kano-spanish-keyboard as well.

@skarbat @tombettany

**Comment by radujipa** [comment]
[Missing keys on Kano Spanish keyboard?](https://trello.com/c/j9LuoVWl/78-missing-keys-on-kano-spanish-keyboard)

**Comment by radujipa** [comment]
[[Settings] Teach the Kano Kit about the Spanish version of the Kano keyboard / Check that it has already happened](https://trello.com/c/VrC2vD2m/56-settings-teach-the-kano-kit-about-the-spanish-version-of-the-kano-keyboard-check-that-it-has-already-happened)

**Comment by skarbat** [comment]
👍  @radujipa perhaps a FIXME label somewhere to remember the subtle fix?

**Comment by radujipa** [comment]
Good point @skarbat, I've added a comment 👍

**Comment by skarbat** [comment]
Thanks Radu! 👍

**Pull request merged**
