### PR TITLE
Switches to use docopt for kano-settings-cli

### PR DESCRIPTION
**Pull request by tombettany**

### CODE REVIEW

**Comment by alex5imon** [comment]
what's the status of this @tombettany ?

**Comment by tombettany** [comment]
@alex5imon It should replace the original `kano-settings-cli` with no change to how you interact with it - I'm comfortable with merging once we are installing docopt by default.

**Comment by alex5imon** [comment]
Please add PR for installing `docopt` and merge this when ready

**Comment by tombettany** [comment]
There are actually 2 (equivalent) PRs already (https://github.com/KanoComputing/kano-updater/pull/44 and https://github.com/KanoComputing/kano-updater/pull/51) to do this.

**Comment by alex5imon** [comment]
Please merge :+1:

**Pull request merged**
