### PR TITLE
Fixes for tvservice

### PR DESCRIPTION
**Pull request by skarbat**
* Avoid calling tvservice when the audio module is imported
 * Clarified code, return a meaningul response after setting audio output

### CODE REVIEW

**Comment by skarbat** [comment]
@Ealdwulf what do you think? Tested on the RPi with a patched `tvservice` and it doesn't get called at load time anymore.

The paths fix I provided might not have system wise implications me thinks. They are symlinked.

**Comment by Ealdwulf** [comment]
Looks good :shipit:

**Comment by skarbat** [comment]
Thanks @Ealdwulf , merging in

**Comment by Ealdwulf** [comment]
Added to changelog for 3.1.0 Haven't seen it crash after switching back and forth a bunch of times, so marking as done.

**Pull request merged**
