### PR TITLE
Refresh networks immediately after a weak signal screen failure.

### PR DESCRIPTION
**Pull request by wizofe**
Bug: 1619 - Wifi No Refresh Issue

Redirect user to the network refresh screens in the gui wifi settings dialogue after a connection failure because of a "weak signal". 

Additionally, modified the .gitignore to include Emacs and VSCode files and dirs.

### CODE REVIEW

**Comment by wizofe** [comment]
[[P3] If wifi connection times out, network list is empty](https://trello.com/c/4uNeppMT/1619-p3-if-wifi-connection-times-out-network-list-is-empty)

**Comment by wizofe** [comment]
🔧 `changelog` updated
©️ received. Do you have any script updating all the headers with current copyright note or should I do manually?

**Comment by radujipa** [comment]
We haven't made a script for it TBH, we just bump the years manually when going into a file (when we remember...) for now

**Comment by wizofe** [comment]
I am working on it. Just made a sed one-liner but I need to make it work with git status -s or smth. I'll keep you updated.

**Comment by tombettany** [comment]
Looks great now. Since the changes for 3.14.1, you'll need to fetch the `master` branch and rebase on it to get this clean and for us to be able to merge.

**Pull request merged**
