### PR TITLE
Parental: Whitelist speaker claim page

### PR DESCRIPTION
**Pull request by tombettany**
The form used to claim the CKC speaker redirects to a page which would
be blocked by the ultimate parental settings. Prevent this from
happening by adding this URL to the whitelist.

### CODE REVIEW

**Comment by tombettany** [comment]
[(1) As a CKC v1.0 user with ultimate parental settings enabled, I want to be able to access the claim your speaker page [1]](https://trello.com/c/DWsWggfc/1477-1-as-a-ckc-v10-user-with-ultimate-parental-settings-enabled-i-want-to-be-able-to-access-the-claim-your-speaker-page-1)

**Comment by tombettany** [comment]
A note on this, the local copy of this file is only updated when the parental settings change so it will only actually unblock the site if the parental settings were enabled after we pushed this fix :-s

**Comment by radujipa** [comment]
But then at least our response can be "please update"

**Comment by radujipa** [comment]
Also, please remember to add a note in the `debian/changelog` for all these PRs.

**Comment by tombettany** [comment]
Added changelog entry

**Pull request merged**
