### PR TITLE
Add disconnect wifi option

### PR DESCRIPTION
**Pull request by carolineclark**
The command ```sudo kano-wifi-gui --disconnect``` will now disconnect the user from the internet if they are connected to WiFi.

Added a disconnect option to the internet widget.
kano-screenshot-mon-may-11-17-58-30

When clicking disconnect, this launches a dialog once the process is finished:
kano-screenshot-mon-may-11-18-00-02

Added a beautiful Disconnect button to the GUI when the user is connected via WiFi.  Will change when @TommySaehl has a design, the placement does look a bit weird.
kano-screenshot-mon-may-11-18-12-31

This is nearly complete, but needs some more refining with ethernet connections - for example, the Disconnect option in the internet widget should only be shown when connected to WiFi.

Needs this pull request to work: https://github.com/KanoComputing/kano-toolset/pull/131

### CODE REVIEW

**Comment by alex5imon** [comment]
@carolineclark great work! Two things:
1) Ask @mkeegan for the copy of that dialogue
2) You are right, disconnect shouldn't be an option when using Ethernet

**Comment by mkeegan** [comment]
Copy:

```Disconnect complete - you're now offline.```

**Comment by carolineclark** [comment]
I think this is ready to review.  @skarbat if you could review this PR, especially the C code, that would be amazing.
One thought - if connected to WiFi, we could also add a Configure option in the wifi widget, which would launch the wifi-gui.

**Comment by skarbat** [comment]
the rest looks great to me @carolineclark

**Comment by alex5imon** [comment]
Please merge :+1:

**Comment by TommySaehl** [comment]
image
Thoughts?

**Comment by alex5imon** [comment]
Seems a bit too prominent for me, seems like there is an error (more visible than the green tick)

**Comment by TommySaehl** [comment]
Selecting an already established connection in the networks list should change the button from *Connect* to a red *Disconnect*.

**Comment by alex5imon** [comment]
I like that

**Pull request merged**
