### PR TITLE
Added screensaver page

### PR DESCRIPTION
**Pull request by carolineclark**
- Shows the current list of screensavers (one).
 - Gives the user the options to change the idle time until it starts, or to switch it off completely.
 - Refactored wallpaper page

kano-screenshot-thu-mar-12-15-18-05
kano-screenshot-thu-mar-12-15-18-20

https://github.com/KanoComputing/peldins/issues/1453

### CODE REVIEW

**Comment by alex5imon** [comment]
Looks really cool @carolineclark 

Just a couple of comments:
- Specify the time unit in screensaver advanced
- Add a button to reset the whole "appearance". Maybe in a new "general" tab?

**Comment by carolineclark** [comment]
"Add a button to reset the whole "appearance"."  Presumably by this, you are referring to the lxpanel config in kano-desktop?  How do we replace this?  Should we create a backup copy of this in kano-desktop, and replace the edited one with it if the user screws it up?
Of course, if they screw up the toolbar very badly, they may not be able to get to kano-settings.

**Comment by alex5imon** [comment]
@carolineclark I'm talking about the UI for this ticket: https://github.com/KanoComputing/peldins/issues/1682

**Comment by carolineclark** [comment]
Ok, so you want a big RESET button (red?) on a separate tab.  Okidoki.

**Comment by carolineclark** [comment]
A button.

kano-screenshot-thu-mar-12-17-37-48

It looks a bit empty though.  If you want a big red button (because we need some big red buttons somewhere.)

kano-screenshot-thu-mar-12-17-53-24

kano-screenshot-thu-mar-12-17-38-00

**Pull request merged**
