### PR TITLE
Parental fix

### PR DESCRIPTION
**Pull request by alex5imon**
https://github.com/KanoComputing/peldins/issues/1971

### CODE REVIEW

**Comment by alex5imon** [comment]
@rluz to send over the new cookies for Google

**Comment by rluz** [comment]
@alex5imon [Cookies PR](https://github.com/KanoComputing/kano-video/pull/65)

**Comment by alex5imon** [comment]
@carolineclark can you please review code and new copy?

**Comment by carolineclark** [comment]
Small problem with the parental control slider moving sideways you hit the different levels because the description goes bold. although I'm not sure of a simple fix (maybe making the description colour darker instead?)
Other than that, looks fine.

**Comment by alex5imon** [comment]
@carolineclark, I have fixed the problem of the slider moving sideways by changing the colour of the font, rather than making it **bold**

**Pull request merged**
