### PR TITLE
[WIP] Prototype for a system wide package integrity check

### PR DESCRIPTION
**Pull request by radujipa**
This is a work in progress. Do not merge.

Sample output:

```
radu@radu ~ $ sudo ./system-integrity -k
Verifying kano-app-launcher.. ok.
Verifying kano-app-launcher-common.. ok.
Verifying kano-applets.. ok.
Verifying kano-apps.. ok.
Verifying kano-blocks.. ok.
Verifying kano-connect.. ok.
Verifying kano-content.. ok.
Verifying kano-credits.. ok.
Verifying kano-dashboard.. ok.
Verifying kano-dashboard-bin.. ok.
Verifying kano-dashboard-common.. FAIL:
  /usr/bin/kano-dashboard-supervisor
Verifying kano-dashboard-i18n.. ok.
Verifying kano-desktop.. FAIL:
  /etc/asound.conf
Verifying kano-draw.. ok.
Verifying kano-feedback.. FAIL:
  /usr/lib/python2.7/dist-packages/kano_feedback/DataSender.py
  /usr/bin/kano-feedback-cli
Verifying kano-fonts.. ok.
Verifying kano-greeter.. ok.
Verifying kano-home-button.. ok.
Verifying kano-i18n.. ok.
Verifying kano-init.. FAIL:
  /usr/share/kano-init/systemd_ttys/kanoautologin@.service
Verifying kano-init-flow.. ok.
Verifying kano-motd.. ok.
Verifying kano-notifications.. ok.
Verifying kano-os.. ok.
Verifying kano-overworld.. ok.
Verifying kano-peripherals.. ok.
Verifying kano-profile.. FAIL:
  /usr/share/applications/defaults.list
Verifying kano-qt-apps.. ok.
Verifying kano-qt-sdk.. ok.
Verifying kano-qt-sdk-core.. ok.
Verifying kano-screenshot.. ok.
Verifying kano-settings.. FAIL:
  /usr/lib/python2.7/dist-packages/kano_settings/set_display.py
  /usr/lib/python2.7/dist-packages/kano_settings/paths.py
  /usr/bin/kano-capture-logs
Verifying kano-sound-files.. ok.
Verifying kano-themes.. ok.
Verifying kano-toolset.. FAIL:
  /usr/lib/python2.7/dist-packages/kano/gtk3/kano_dialog.py
  /usr/lib/python2.7/dist-packages/kano/utils/file_operations.py
Verifying kano-updater.. ok.
Verifying kano-video.. FAIL:
  /usr/share/applications/auto_video-cli.desktop
Verifying kano-video-files.. ok.
Verifying kano-vnc.. ok.
Verifying kano-wallpapers.. ok.
Verifying kano-wallpapers-data.. ok.
Verifying kano-webengine.. ok.
Verifying kano-widgets.. ok.
Verifying kano2-app.. ok.
Verifying make.. ok.
Verifying make-apps.. ok.
Verifying make-light.. ok.
Verifying make-minecraft.. ok.
Verifying make-minecraft-basic-world.. ok.
Verifying make-minecraft-intro-video.. ok.
Verifying make-minecraft-server.. ok.
Verifying make-music.. ok.
Verifying make-pong.. ok.
Verifying make-snake.. FAIL:
  /usr/share/applications/make-snake.app
Verifying makedev.. ok.

The following packages have changes:
{
    "kano-dashboard-common": [
        "/usr/bin/kano-dashboard-supervisor"
    ], 
    "kano-desktop": [
        "/etc/asound.conf"
    ], 
    "kano-feedback": [
        "/usr/lib/python2.7/dist-packages/kano_feedback/DataSender.py", 
        "/usr/bin/kano-feedback-cli"
    ], 
    "kano-init": [
        "/usr/share/kano-init/systemd_ttys/kanoautologin@.service"
    ], 
    "kano-profile": [
        "/usr/share/applications/defaults.list"
    ], 
    "kano-settings": [
        "/usr/lib/python2.7/dist-packages/kano_settings/set_display.py", 
        "/usr/lib/python2.7/dist-packages/kano_settings/paths.py", 
        "/usr/bin/kano-capture-logs"
    ], 
    "kano-toolset": [
        "/usr/lib/python2.7/dist-packages/kano/gtk3/kano_dialog.py", 
        "/usr/lib/python2.7/dist-packages/kano/utils/file_operations.py"
    ], 
    "kano-video": [
        "/usr/share/applications/auto_video-cli.desktop"
    ], 
    "make-snake": [
        "/usr/share/applications/make-snake.app"
    ]
}
```

### CODE REVIEW

**Comment by radujipa** [comment]
[(3) As a user, I want to be able to checking if my SD is corrupted [3]](https://trello.com/c/hcs7dftx/1741-3-as-a-user-i-want-to-be-able-to-checking-if-my-sd-is-corrupted-3)

**Comment by radujipa** [comment]
[(3) As a user, I want to be able to checking if my SD is corrupted [3]](https://trello.com/c/hcs7dftx/1741-3-as-a-user-i-want-to-be-able-to-checking-if-my-sd-is-corrupted-3)

**Comment by skarbat** [comment]
Cool! Would it make sense for this guy to go into kano-updater instead?

**Comment by radujipa** [comment]
Replaced by https://github.com/KanoComputing/kano-settings/pull/515

**Pull request closed without merging**
