### PR TITLE
Bluetooth: Add interface for configuring devices

### PR DESCRIPTION
**Pull request by tombettany**
Add ability to detect Bluetooth capabilities and pair with nearby
devices.

Requires:
 - https://github.com/KanoComputing/kano-toolset/pull/190
 - https://github.com/KanoComputing/kano-toolset/pull/191
 - https://github.com/KanoComputing/kano-toolset/pull/192

cc @radujipa @convolu @Ealdwulf 

Detected Devices List:

kano-screenshot-mon-feb-22-14-14-48

Scanning/Connecting Screen:

kano-screenshot-mon-feb-22-14-14-54

Device Connected Screen:

kano-screenshot-mon-feb-22-14-15-04

### CODE REVIEW

**Comment by alex5imon** [comment]
@tombettany can you add a screenshot? @neue will need to review the design

**Comment by radujipa** [comment]
Very neat, Mr Bettany! :shipit:

**Comment by convolu** [comment]
Those decorators make it so much more readable

**Comment by convolu** [comment]
Looks ok to me

**Comment by tombettany** [comment]
I will merge this now to fully test the functionality but @neue can you leave comments on the screenshots that I posted above and put the bluetooth icon in here and I will create another PR to correct the things that you don't like.

**Comment by neue** [comment]
bluetooth

@tombettany only things really are the grey on orange refresh icon is a bit weird (if we only have a grey version of this asset I'll create a white one if you point me in the right direction). 

and the "unpair" button should be red I reckon.

**Comment by tombettany** [comment]
@neue That would be great - here is the [refresh icon](https://github.com/KanoComputing/kano-settings/blob/jessie/media/kano-settings/Graphics/refresh.png). I'll make the other changes that you suggested.

**Comment by neue** [comment]
refresh

The refresh icon is above this text (May be invisible because white on white)

**Comment by tombettany** [comment]
Thanks :)

**Pull request merged**
